heat_template_version: 2016-10-14

description: Template create volume.

#####################################
# PARAMETERS
#####################################
parameters:
  name:
    label: Volume Name
    type: string
    description: the name of volume
  size:
    label: Volume Size
    type: string
    description: the size of volume in GB
  volume_type:
    label: Volume Type
    type: string
    description: the type of volume

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      name: {get_param: name}
      size: {get_param: size}
      volume_type: {get_param: volume_type}
      metadata: {neo_type: NVC2}

outputs:
  id: { get_resource: volume }
  name: { get_attr: [ volume,display_name ] }
  status: { get_attr: [ volume,status ] }
  size: { get_attr: [ volume,size ] }
  volume_type: { get_attr: [ volume,volume_type ] }
  attachment: { get_attr: [ volume,attachments ] }
  metadata: { get_attr: [ volume,metadata ] }