heat_template_version: 2016-10-14

description: Template create volume.

#####################################
# PARAMETERS
#####################################
parameters:
  volume_size:
    label: Volume Size
    type: number
    description: the size of volume in GB
  volume_type:
    label: Volume Type
    type: string
    description: the type of volume

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      name: { get_param: 'OS::stack_name' }
      size: {get_param: volume_size}
      volume_type: {get_param: volume_type}
      metadata: {neo_type: NVC2}

outputs:
  volume_id: 
    description: Volume ID
    value: { get_resource: volume }
  volume_name: 
    description: Volume name
    value: { get_attr: [ volume,display_name ] }
  volume_status:
    description: Volume status
    value: { get_attr: [ volume,status ] }
  volume_size: 
    description: Volume size
    value: { get_attr: [ volume,size ] }
  volume_type: 
    description: Volume type
    value: { get_attr: [ volume,volume_type ] }
  volume_attachment: 
    description: Volume attachments
    value: { get_attr: [ volume,attachments_list] }
  volume_metadata: 
    description: Volume metadata
    value: { get_attr: [ volume,metadata ] }